### ISSUE TITLE
Please add Hacktoberfest label to the repository.

### ISSUE THREAD

**Issue by jaldhar** [manwar/perlweeklychallenge-club#2451]
Hacktoberfest is opt-in this year.  Could you please add the label so we can get those sweet sweet t-shirts. :-)

**Comment by manwar** [comment]
Done.
Is it good to go now?

**Comment by jaldhar** [comment]
I'm not seeing it.  I think I might have misunderstood the instructions from Digital Ocean.  This is not a label for issues, though you can do that but a "topic".  On the repository page, click on the wheel icon next to "About" and add "hacktoberfest" under "topics".  I think that should do it.

**Comment by oWnOIzRi** [comment]
@manwar I think there is a typeo in your hacktoberfest label.  Also their website says it is looking for the "hacktoberfest-accepted" label against a pull request.  Thank you.

**Comment by polettix** [comment]
![hacktoberfest labeling](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif)

Note that `hacktoberfest` is all lowercase 😉

**Comment by manwar** [comment]
Thanks @polettix 
All done :-)

**Comment by jaldhar** [comment]
Confirmed.  We can close this issue now.

**Comment by manwar** [comment]
Closing it now as confirmed by @jaldhar
