### ISSUE TITLE
Challenge solutions not compliant

### ISSUE THREAD

**Issue by pauloscustodio** [manwar/perlweeklychallenge-club#3772]
One of the PWC members submitted a solution in Bash to challenge 104 like this:
echo "0 1 1 2 1 3 2 3 1 4 3 5 2 5 3 4 1 5 4 7 3 8 5 7 2 7 "\
"5 8 3 7 4 5 1 6 5 9 4 11 7 10 3 11 8 13 5 12 7 9 2 9"

This is not generating the sequence of the 50 first FUCS numbers as requested.

Should this be accepted as a valid solution? What if someone writes a program in Perl to output code in N languages to just print the result of the Perl computation?

**Comment by manwar** [comment]
There is no strict rule how you get it. Feel free to find your own way.
I am sure, Colin would have something to talk about in his review. :-)
