### ISSUE TITLE
This program finds a sequence of only 14 words with Mohammad's input list

### ISSUE THREAD

**Issue by LaurentRosenfeld** [manwar/perlweeklychallenge-club#622]
This program apparently finds a best sequence of only 14 words with Mohammad's input list, and this is (IMHO) wrong. As far as I can say, the longest sequence has at least 23 words, and there are more than two thousand such sequences.

Note: If this Github issue goes to Mohammad, then, @Mohammad: please transmit to Simon, I don't have an email address to communicate directly with Simon. @Mohammad: please feel free to give my e-mail address to Simon to enable direct mail exchange.

Best regards to both of you,
Laurent.

**Comment by manwar** [comment]
@LaurentRosenfeld you can reach out to Scimon here:

https://github.com/Scimon

**Comment by manwar** [comment]
Closing the issue now. :-)
