### ISSUE TITLE
Missed blog posts for Avery Adams 210.

### ISSUE THREAD

**Issue by oldtechaa** [manwar/perlweeklychallenge-club#7844]
I put my blog post links in my PR. Can those be added to the recap please?

**Comment by oldtechaa** [comment]
Blog posts can be found [here](https://dev.to/oldtechaa/perl-weekly-challenge-210-1ojj) and [here](https://blogs.perl.org/users/oldtechaa/2023/03/perl-weekly-challenge-210.html).

**Comment by manwar** [comment]
Sorry for late response, this has been resolved. Thanks for reporting.
https://theweeklychallenge.org/blog/recap-challenge-210/#PERLSOLUTIONS
