### ISSUE TITLE
Wrong language Adb

### ISSUE THREAD

**Issue by pauloscustodio** [manwar/perlweeklychallenge-club#9150]
In the statistics (e.g. https://theweeklychallenge.org/blog/recap-challenge-244/) it is said that I have contributed with:
```Ada (20), Adb (1), ...```

In fact it's 21 Ada, Adb is the file extension of Ada code.

**Comment by manwar** [comment]
Thanks for reporting the error.
It has been fixed now.
https://theweeklychallenge.org/blog/recap-challenge-244/
